# Generated by Django 5.1.1 on 2024-10-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('diagnoses', models.TextField()),
            ],
        ),
    ]
