# Generated by Django 5.1.1 on 2024-10-07 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_disease', models.CharField(max_length=200)),
                ('symptoms', models.TextField()),
                ('precautions', models.TextField()),
                ('medications', models.TextField()),
                ('recommended_diet', models.TextField()),
                ('workout', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
